#!/bin/bash

GADWALL=$(readlink -f $(dirname $0)/..)

git remote add -f gadwall $GADWALL
git merge -s ours --no-commit gadwall/master
git read-tree -m -u gadwall/master
cp README docs/README.gadwall
git add docs/README.gadwall
git reset HEAD README
git checkout -f README
git commit -m "Import a copy of Gadwall"
