#!/bin/bash

source schema/defs || exit
PSQL=${PSQL:-psql}

SQL="schema/*.sql $@"
set -- $SQL
shift

echo "Creating users, database, and schema..."
su -m postgres -c $PSQL <<SQL
\set ON_ERROR_STOP
SET client_min_messages TO 'error';
CREATE USER $USER;
CREATE USER $ADMIN;
CREATE DATABASE $DB WITH OWNER $ADMIN;
\c $DB
\set user $USER
SET client_min_messages TO 'error';
CREATE OR REPLACE LANGUAGE plpgsql;
\i schema/000-extensions.sql
SET SESSION AUTHORIZATION $ADMIN;
begin;
$(for i in "$@"; do echo "\\i $i"; done)
commit;
SQL
